export { faPalette } from "@fortawesome/free-solid-svg-icons/faPalette";
export { faCode } from "@fortawesome/free-solid-svg-icons/faCode";
export { faSchool } from "@fortawesome/free-solid-svg-icons/faSchool";
export { faPenNib } from "@fortawesome/free-solid-svg-icons/faPenNib";
export { faUserFriends } from "@fortawesome/free-solid-svg-icons/faUserFriends";
export { faLaptop } from "@fortawesome/free-solid-svg-icons/faLaptop";
export { faInstagram } from "@fortawesome/free-brands-svg-icons/faInstagram";
export { faTwitter } from "@fortawesome/free-brands-svg-icons/faTwitter";
export { faGithub } from "@fortawesome/free-brands-svg-icons/faGithub";
